name: filmtok
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  google_sign_in: ^6.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: lib/fonts/Euclid_Circular_A_Regular.ttf
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Regular.ttf  
       
