// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4NWnfOjqxZwjHb_1eQdUIYwiEvJ09YI',
    appId: '1:531502539289:web:189ba74f35bbd1d6684088',
    messagingSenderId: '531502539289',
    projectId: 'login-page-7dcf7',
    authDomain: 'login-page-7dcf7.firebaseapp.com',
    storageBucket: 'login-page-7dcf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKSxAwMqCEZOTPNVZhhWf9B1lh8vyfXA',
    appId: '1:531502539289:android:c9f83cfe25f8398d684088',
    messagingSenderId: '531502539289',
    projectId: 'login-page-7dcf7',
    storageBucket: 'login-page-7dcf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqVRsTqauSENPC-IPFcpSWQ7DC4BjDh0',
    appId: '1:531502539289:ios:8355e0b330b32f20684088',
    messagingSenderId: '531502539289',
    projectId: 'login-page-7dcf7',
    storageBucket: 'login-page-7dcf7.firebasestorage.app',
    iosBundleId: 'com.example.filmtok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqVRsTqauSENPC-IPFcpSWQ7DC4BjDh0',
    appId: '1:531502539289:ios:8355e0b330b32f20684088',
    messagingSenderId: '531502539289',
    projectId: 'login-page-7dcf7',
    storageBucket: 'login-page-7dcf7.firebasestorage.app',
    iosBundleId: 'com.example.filmtok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4NWnfOjqxZwjHb_1eQdUIYwiEvJ09YI',
    appId: '1:531502539289:web:f8f7bc48e97a424b684088',
    messagingSenderId: '531502539289',
    projectId: 'login-page-7dcf7',
    authDomain: 'login-page-7dcf7.firebaseapp.com',
    storageBucket: 'login-page-7dcf7.firebasestorage.app',
  );
}
